### ISSUE TITLE
Simple example?

### ISSUE THREAD

**Issue by ignatandrei** [barncastle/BitsKit#1]
I want to add this to my list of Roslyn Source Code Generator 

https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG

but I need a simple example of why it is usefull .

Could you help me please?

**Comment by ignatandrei** [comment]
?

**Comment by barncastle** [comment]
Thanks for your interest in this project! Apologies for the delayed response I've been moving house

Great question! The main point of the project is to simplify working with bits in C# which requires a fair amount of time and effort. The source generator is used to generate "bitfield" properties that can get/set specific bits within a type. Bitfields are quite niche and are mostly used in memory critical environments like microcontrollers (where memory is scarce) and network code (where egress is expensive) - the latter now quite common thanks to Unity based multiplayer games

To give a simple real world example: below is the ZLib header which consists of 5 bitfields across 2 bytes. 

In C and C++ you can specify how many bits each field consumes within a struct such as:

```c
struct
{
  uint8_t CM : 4       // compression method, 4 bits
  uint8_t CINFO : 4    // compression info, 4 bits

  uint8_t FCHECK : 5   // check bits, 5 bits
  uint8_t FDICT : 1    // use preset dictionary, 1 bit
  uint8_t FLEVEL : 2   // compression level, 2 bits
} zlib_header
```

Since C# doesn't allow this, you have to write the following:
  
```c#
struct zlib_header
{
  public byte CM         // first 4 bits of CMF
  {
    get => (byte)(CMF & 0xF);
    set => CMF = (byte)((CMF & ~0xF) | (value & 0xF));
  }

  public byte CINFO      // last 4 bits of CMF
  {
    get => (byte)(CMF & 0xF0);
    set => CMF = (byte)((CMF & ~0xF0) | ((value & 0xF) << 4));
  }

  private byte CMF;
  
  public byte FCHECK     // first 5 bits of FLG
  {
    get => (byte)(FLG & 0x1F);
    set => FLG = (byte)((FLG & ~0x1F) | (value & 0x1F));
  }

  public byte FDICT      // 6th bit of FLG
  {
    get => (byte)(FLG & 0x20);
    set => FLG = (byte)((FLG & ~0x20) | ((value & 1) << 5));
  }

  public byte FLEVEL     // last 2 bits of FLG
  {
    get => (byte)(FLG & 0xC0);
    set => FLG = (byte)((FLG & ~0xC0) | ((value & 3) << 6));
  }

  private byte FLG;
}
```

As you can see, this is a lot of code for just 5 fields and none of it is overly intuitive. BitsKit tackles both these problems by using source generators to auto-generate these properties behind the scenes. This simplifies the user's code to just specifying each bitfield's name and size - almost like in C. 

Using BitsKit this would be written as:

```c#
[BitObject(BitOrder.LeastSignificant)]
struct zlib_header
{
  [BitField("CM", 4)]
  [BitField("CINFO", 4)]
  private byte CMF;

  [BitField("FCHECK", 5)]
  [BitField("FDICT", 1)]
  [BitField("FLEVEL", 2)]
  private byte FLG;
}
```

This project also takes it one step further adding features missing from the C bitfield spec such as; defining bit order, mixing bitfield types and supporting Enum bitfields. Utilising these features produces a much more intuitive and descriptive structure:

```c#
[BitObject(BitOrder.LeastSignificant)]
struct zlib_header
{
  [EnumField("CM", 4, typeof(CompressionMethod))]
  [BitField("CINFO", 4)]
  private byte CMF;

  [BitField("FCHECK", 5)]
  [BooleanField("FDICT")]
  [EnumField("FLEVEL", 2, typeof(CompressionLevel))]
  private byte FLG;
}
```

I hope this gives you what you need. My plan is to get this updated to .Net 8 and on Nuget in the next week or so too. Let me know if you have any questions

By the way, your project is awesome! Super useful :)

**Comment by ignatandrei** [comment]
Thanks! I will make an example ASAP!

**Comment by ignatandrei** [comment]
Sorry, I cannot find the nuget . Could you provide the link ?
Thanks!

**Comment by ignatandrei** [comment]
?

**Comment by barncastle** [comment]
Sorry still moving house! 

First version is published to Nuget and a link has been added to the README. Let me know if I've missed anything or it doesn't work etc. I've not had much experience with publishing to Nuget :)
